name: adiubear
description: "The project for GDGoC Solution Challenge."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.5.0+2

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  image_picker: ^1.0.4
  speech_to_text: ^7.0.0
  flutter_localizations:
    sdk: flutter
  permission_handler: ^12.0.0+1
  firebase_core: ^3.13.0
  intl: any
  firebase_vertexai: ^1.6.0
  record: ^6.0.0
  path_provider: ^2.1.5
  flutter_markdown: ^0.7.7+1
  flutter_chat_core: ^2.0.0
  flutter_chat_ui: ^2.0.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # Synthetic package output (package:flutter_gen) is deprecated: https://flutter.dev/to/flutter-gen-deprecation.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/resources/
