// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOkmt-t3GSP_dSMbePmTl-GmBBfbWq8WQ',
    appId: '1:636726337012:web:57085e27e23dac1a7ceda1',
    messagingSenderId: '636726337012',
    projectId: 'gen-lang-client-0514711078',
    authDomain: 'gen-lang-client-0514711078.firebaseapp.com',
    storageBucket: 'gen-lang-client-0514711078.firebasestorage.app',
    measurementId: 'G-K43ZVR1YMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcjjDnXJt8jhAN2S5tG2wRx07fYSqOoHE',
    appId: '1:636726337012:android:9ef0c89be4a0b96e7ceda1',
    messagingSenderId: '636726337012',
    projectId: 'gen-lang-client-0514711078',
    storageBucket: 'gen-lang-client-0514711078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvtYVh8-V4751Krlhkco6bScEtkzcTwZQ',
    appId: '1:636726337012:ios:b3cb4a2161064f497ceda1',
    messagingSenderId: '636726337012',
    projectId: 'gen-lang-client-0514711078',
    storageBucket: 'gen-lang-client-0514711078.firebasestorage.app',
    androidClientId: '636726337012-ob4jg7odqcvfbk8c13gsmvbqqht3rm2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvtYVh8-V4751Krlhkco6bScEtkzcTwZQ',
    appId: '1:636726337012:ios:b3cb4a2161064f497ceda1',
    messagingSenderId: '636726337012',
    projectId: 'gen-lang-client-0514711078',
    storageBucket: 'gen-lang-client-0514711078.firebasestorage.app',
    androidClientId: '636726337012-ob4jg7odqcvfbk8c13gsmvbqqht3rm2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOkmt-t3GSP_dSMbePmTl-GmBBfbWq8WQ',
    appId: '1:636726337012:web:4785ea9a5a2b5e207ceda1',
    messagingSenderId: '636726337012',
    projectId: 'gen-lang-client-0514711078',
    authDomain: 'gen-lang-client-0514711078.firebaseapp.com',
    storageBucket: 'gen-lang-client-0514711078.firebasestorage.app',
    measurementId: 'G-QX6F4JV4S7',
  );

}